In [1]:
import pandas as pd
import scipy.stats as st
from datetime import datetime
from datetime import timedelta
import math
import numpy as np
from scipy import stats
import copy
from PIL import Image
import imageio

In [53]:
a = [[0, 0, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 1, 0, 0],
    [0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 1, 0],
    [0, 0, 0, 0, 0, 0, 0]]

b = [[0, 1, 0, 0, 0, 0, 0],
    [0, 1, 0, 0, 1, 0, 0],
    [0, 0, 1, 0, 0, 0, 0],
    [0, 0, 0, 1, 0, 0, 0],
    [0, 0, 0, 0, 0, 0, 0],
    [0, 0, 0, 0, 0, 1, 0],
    [0, 0, 0, 0, 0, 0, 0]]

a = np.asarray(a)
b = np.asarray(b)



[[[0. 0. 0. 0. 0. 0. 0.]
  [0. 1. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0. 0. 0.]]

 [[0. 1. 0. 0. 0. 0. 0.]
  [0. 1. 0. 0. 1. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0. 0. 0.]]]

0.00 0.50 0.00 0.00 0.50 0.00 0.00 
0.50 1.00 0.50 0.50 1.00 0.50 0.00 
0.00 0.50 0.00 0.00 0.50 0.00 0.00 
0.00 0.00 0.00 0.00 0.00 0.00 0.00 
0.00 0.00 0.00 0.00 0.00 0.50 0.00 
0.00 0.00 0.00 0.00 0.50 1.00 0.50 
0.00 0.00 0.00 0.00 0.00 0.50 0.00 

0.50 1.50 0.50 0.00 0.50 0.00 0.00 
0.50 1.50 1.00 0.50 1.00 0.50 0.00 
0.00 1.00 1.00 1.00 0.50 0.00 0.00 
0.00 0.00 1.00 1.00 0.50 0.00 0.00 
0.00 0.00 0.00 0.50 0.00 0.50 0.00 
0.00 0.00 0.00 0.00 0.50 1.00 0.50 
0.00 0.00 0.00 0.00 0.00 0.50 0.00 

generate_imageee method in...
이미지 저장 전 구조: (7, 7)
